language: go
env: HUGO_VERSION=0.49.2
notifications:
  email:
    on_success: change
    on_failure: change

install:
  - wget -O "./hugo.tar.gz" "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
  - tar -xvzf ./hugo.tar.gz

script:
  - ./hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  on:
    branch: source

