title = "LibrePCB"
languageCode = "en-us"

# We need all URLs to be relative to make sure the previews hosted at
# https://librepcb.org/_branches/ are working properly.
relativeURLs = true

# So far we don't use tags and categories, so let's disable it for now.
[taxonomies]

# Disable RSS output globally (will be enabled only for the blog).
[outputs]
home = ['HTML']
page = ['HTML']
section = ['HTML']
taxonomy = ['HTML']
term = ['HTML']

# Custom parameters.
[params]
  topBlockTitle = "LibrePCB"
  topBlockDescription = "A new, powerful and intuitive EDA tool for everyone."
  mainIcon = "img/librepcb.png"
  blogTitle = "LibrePCB Blog"
  latestVersion = "0.1.7"
