baseurl = "http://librepcb.org"
languageCode = "en-us"
title = "LibrePCB"
[params]
  topBlockTitle = "LibrePCB"
  topBlockDescription = ""
  mainIcon = "img/librepcb.png"
  blogTitle = "LibrePCB Blog"
