baseurl = "http://librepcb.org"
languageCode = "en-us"
title = "LibrePCB"
[params]
  topBlockTitle = "LibrePCB"
  topBlockDescription = "A new, powerful and intuitive EDA tool for everyone."
  mainIcon = "img/librepcb.png"
  blogTitle = "LibrePCB Blog"
  latestVersion = "0.1.0"
