# We need all URLs to be relative to make sure the previews hosted at
# https://librepcb.org/_branches/ are working properly.
relativeURLs = true

languageCode = "en-us"
title = "LibrePCB"
[params]
  topBlockTitle = "LibrePCB"
  topBlockDescription = "A new, powerful and intuitive EDA tool for everyone."
  mainIcon = "img/librepcb.png"
  blogTitle = "LibrePCB Blog"
  latestVersion = "0.1.5"
